- name: Provision hadoop name node
  local_action: ec2  keypair={{ mykeypair }} instance_type={{ instance_type }} image={{ image }} wait=true zone={{ zone }} region={{ region }} instance_tags='{"name":"{{ item }}"}' wait_timeout=600
  register: ec2
  with_items:
    - "hadoop-name"
    - "hadoop-data"

- name: Print new instance details
  debug: var=ec2

- name: Wait for SSH to come up
  local_action: wait_for host={{ item.instances[0]['public_dns_name'] }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.results

- name: Add new instance to host group
  add_host: hostname={{ item.instances[0]['public_ip'] }} groupname=launched instance_hostname={{ item.item }} user=ec2-user
  with_items: ec2.results

