---  
-   hosts: "{{ nodes }}"
    remote_user: ec2-user
    tasks:
       - name: Restart hadoop-hdfs-datanode service
         service: name=hadoop-hdfs-datanode state=restarted
         sudo: yes

