---
- hosts: web001
  remote_user: ec2-user
  gather_facts: no
  tasks:
    - name: give users access to multiple databases
      mysql_user: name={{ item[0] }} priv={{ item[1] }}.*:ALL append_privs=yes password=foo login_user=root login_password=root
      with_nested:
        - ['alice', 'bob']
        - ['clientdb', 'employeedb', 'providerdb']

