- name: Checkout git repo
  git: repo=https://github.com/madhurranjan/ember-simple-auth-rails-demo.git
       dest={{ app_dir }}
  sudo: yes
       
- name: Change permissions of folder
  sudo: yes
  file: path={{ app_dir }} owner=ec2-user group=ec2-user recurse=yes state=directory

- name: Install gems via bundler
  command: bundle install chdir={{ app_dir }}

- name: Setup database.yml
  template: src=database.yml dest={{ app_dir }}/config/database.yml owner=ec2-user group=ec2-user mode=0644

- name: Set SECRET_KEY_BASE environment variable
  template: src=secret.sh dest=/etc/profile.d/secret.sh owner=root group=ec2-user mode=0644
  sudo: yes

- name: Run rake db:create
  shell: bundle exec /home/ec2-user/bin/rake db:create RAILS_ENV={{ rails_env }} chdir={{ app_dir }}
  
- name: Run rake db:migrate
  shell: bundle exec /home/ec2-user/bin/rake db:migrate RAILS_ENV={{ rails_env }} chdir={{ app_dir }}

- name: Run rake assets:precompile
  shell: bundle exec /home/ec2-user/bin/rake assets:precompile RAILS_ENV={{ rails_env }} RAILS_GROUPS=assets chdir={{ app_dir }}

- name: Setup unicorn.rb 
  template: src=unicorn.rb dest={{ app_dir }}/config/unicorn.rb owner=ec2-user group=ec2-user mode=0644

- name: Start service
  shell: bundle exec /home/ec2-user/bin/unicorn_rails -p {{ app_port }} -E {{ rails_env }} -c {{ app_dir }}/config/unicorn.rb -d -D chdir={{ app_dir }}
