# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "devbase"
  
  config.vm.define :node1 do |machine|
    machine.vm.network :forwarded_port, guest: 80, host: 8082
    machine.vm.network :private_network, ip: "192.168.33.10"
    machine.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "inventory"
      ansible.playbook = "build_agent.yml"
      ansible.sudo = true
      ansible.limit = 'all'
    end
  end
 
  config.vm.define :node2 do |machine|
    machine.vm.network :forwarded_port, guest: 80, host: 8083
    machine.vm.network :private_network, ip: "192.168.33.11"
    machine.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "inventory"
      ansible.playbook = "cassandra.yml"
      ansible.sudo = true
      ansible.limit = 'all'
    end
  end
end
