---
- name : Check if epel.repo exists
  stat: path=/etc/yum.repos.d/epel.repo
  register: repo

- name: Add epel yum repo
  shell: rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  when: repo.stat.exists != true

- name: Add content to /etc/hosts
  lineinfile: dest=/etc/hosts state=present line="{{ ansible_eth0.ipv4.address }} sample_app"


- name: Install nginx package
  yum: name=nginx state=latest

- name: Start nginx server
  service: name=nginx state=started

- name: Copy nginx conf
  template: src=sample_app.conf dest=/etc/nginx/conf.d/nginx.conf owner=nginx group=nginx mode=0644
  notify: restart nginx
