---
  - name: download maven 
    get_url: url=${maven_url} dest=/opt thirsty=no
    tags:
      - maven

  - name: untar maven 
    shell: cd /opt; tar -zxvf ${maven_software} creates=/opt/${maven_base_directory}
    tags:
      - maven

  - name: add maven file to etcprofiles
    template: src=maven.sh dest=/etc/profile.d
    tags:
      - maven
