---  
- hosts: host1
  remote_user: ec2-user
  tasks:

    - name: Install httpd package
      yum: name=httpd state=latest
      sudo: yes
     
    - name: Check httpd service
      service: name=httpd state=started
      sudo: yes

    - name: Update httpd.conf file
      template: src=/Users/ramesh/httpd.conf_web dest=/etc/httpd/conf/httpd.conf
      sudo: yes

