---
- hosts: web001
  remote_user: ec2-user
  gather_facts: no
  
  tasks:
    - name: install httpd service
      yum: name=httpd state=latest
      tags:
        - install
      sudo: yes
 
    - name: Stop httpd service
      service: name=httpd state=stopped
      tags:
        - stop
      sudo: yes
 
    - name: Start httpd service
      service: name=httpd state=started
      tags:
        - start
      sudo: yes

